// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swapi/swapi.proto

package swapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilmsRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilmsRequest) Reset()         { *m = FilmsRequest{} }
func (m *FilmsRequest) String() string { return proto.CompactTextString(m) }
func (*FilmsRequest) ProtoMessage()    {}
func (*FilmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{0}
}

func (m *FilmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilmsRequest.Unmarshal(m, b)
}
func (m *FilmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilmsRequest.Marshal(b, m, deterministic)
}
func (m *FilmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilmsRequest.Merge(m, src)
}
func (m *FilmsRequest) XXX_Size() int {
	return xxx_messageInfo_FilmsRequest.Size(m)
}
func (m *FilmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilmsRequest proto.InternalMessageInfo

func (m *FilmsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FilmsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Film struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EpisodeId            string   `protobuf:"bytes,3,opt,name=episodeId,proto3" json:"episodeId,omitempty"`
	Director             string   `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	Producer             string   `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	Edited               string   `protobuf:"bytes,6,opt,name=edited,proto3" json:"edited,omitempty"`
	ReleaseDate          string   `protobuf:"bytes,7,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	OpeningCrawl         string   `protobuf:"bytes,9,opt,name=openingCrawl,proto3" json:"openingCrawl,omitempty"`
	Characters           []int32  `protobuf:"varint,10,rep,packed,name=characters,proto3" json:"characters,omitempty"`
	Planets              []int32  `protobuf:"varint,11,rep,packed,name=planets,proto3" json:"planets,omitempty"`
	Species              []int32  `protobuf:"varint,12,rep,packed,name=species,proto3" json:"species,omitempty"`
	Starships            []int32  `protobuf:"varint,13,rep,packed,name=starships,proto3" json:"starships,omitempty"`
	Vehicles             []int32  `protobuf:"varint,14,rep,packed,name=vehicles,proto3" json:"vehicles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Film) Reset()         { *m = Film{} }
func (m *Film) String() string { return proto.CompactTextString(m) }
func (*Film) ProtoMessage()    {}
func (*Film) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{1}
}

func (m *Film) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Film.Unmarshal(m, b)
}
func (m *Film) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Film.Marshal(b, m, deterministic)
}
func (m *Film) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Film.Merge(m, src)
}
func (m *Film) XXX_Size() int {
	return xxx_messageInfo_Film.Size(m)
}
func (m *Film) XXX_DiscardUnknown() {
	xxx_messageInfo_Film.DiscardUnknown(m)
}

var xxx_messageInfo_Film proto.InternalMessageInfo

func (m *Film) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Film) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Film) GetEpisodeId() string {
	if m != nil {
		return m.EpisodeId
	}
	return ""
}

func (m *Film) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *Film) GetProducer() string {
	if m != nil {
		return m.Producer
	}
	return ""
}

func (m *Film) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Film) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *Film) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Film) GetOpeningCrawl() string {
	if m != nil {
		return m.OpeningCrawl
	}
	return ""
}

func (m *Film) GetCharacters() []int32 {
	if m != nil {
		return m.Characters
	}
	return nil
}

func (m *Film) GetPlanets() []int32 {
	if m != nil {
		return m.Planets
	}
	return nil
}

func (m *Film) GetSpecies() []int32 {
	if m != nil {
		return m.Species
	}
	return nil
}

func (m *Film) GetStarships() []int32 {
	if m != nil {
		return m.Starships
	}
	return nil
}

func (m *Film) GetVehicles() []int32 {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

type FilmsReply struct {
	Films                []*Film  `protobuf:"bytes,1,rep,name=films,proto3" json:"films,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilmsReply) Reset()         { *m = FilmsReply{} }
func (m *FilmsReply) String() string { return proto.CompactTextString(m) }
func (*FilmsReply) ProtoMessage()    {}
func (*FilmsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{2}
}

func (m *FilmsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilmsReply.Unmarshal(m, b)
}
func (m *FilmsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilmsReply.Marshal(b, m, deterministic)
}
func (m *FilmsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilmsReply.Merge(m, src)
}
func (m *FilmsReply) XXX_Size() int {
	return xxx_messageInfo_FilmsReply.Size(m)
}
func (m *FilmsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FilmsReply.DiscardUnknown(m)
}

var xxx_messageInfo_FilmsReply proto.InternalMessageInfo

func (m *FilmsReply) GetFilms() []*Film {
	if m != nil {
		return m.Films
	}
	return nil
}

type PeopleRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleRequest) Reset()         { *m = PeopleRequest{} }
func (m *PeopleRequest) String() string { return proto.CompactTextString(m) }
func (*PeopleRequest) ProtoMessage()    {}
func (*PeopleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{3}
}

func (m *PeopleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleRequest.Unmarshal(m, b)
}
func (m *PeopleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleRequest.Marshal(b, m, deterministic)
}
func (m *PeopleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleRequest.Merge(m, src)
}
func (m *PeopleRequest) XXX_Size() int {
	return xxx_messageInfo_PeopleRequest.Size(m)
}
func (m *PeopleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleRequest proto.InternalMessageInfo

func (m *PeopleRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeopleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BirthYear            string   `protobuf:"bytes,3,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	EyeColor             string   `protobuf:"bytes,5,opt,name=eye_color,json=eyeColor,proto3" json:"eye_color,omitempty"`
	HairColor            string   `protobuf:"bytes,6,opt,name=hair_color,json=hairColor,proto3" json:"hair_color,omitempty"`
	SkinColor            string   `protobuf:"bytes,7,opt,name=skin_color,json=skinColor,proto3" json:"skin_color,omitempty"`
	Height               string   `protobuf:"bytes,8,opt,name=height,proto3" json:"height,omitempty"`
	Mass                 string   `protobuf:"bytes,9,opt,name=mass,proto3" json:"mass,omitempty"`
	Homeworld            int32    `protobuf:"varint,10,opt,name=homeworld,proto3" json:"homeworld,omitempty"`
	Url                  string   `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Created              string   `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,13,opt,name=edited,proto3" json:"edited,omitempty"`
	Films                []int32  `protobuf:"varint,14,rep,packed,name=films,proto3" json:"films,omitempty"`
	Starships            []int32  `protobuf:"varint,15,rep,packed,name=starships,proto3" json:"starships,omitempty"`
	Species              []int32  `protobuf:"varint,16,rep,packed,name=species,proto3" json:"species,omitempty"`
	Vehicles             []int32  `protobuf:"varint,17,rep,packed,name=vehicles,proto3" json:"vehicles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{4}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetBirthYear() string {
	if m != nil {
		return m.BirthYear
	}
	return ""
}

func (m *Person) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Person) GetEyeColor() string {
	if m != nil {
		return m.EyeColor
	}
	return ""
}

func (m *Person) GetHairColor() string {
	if m != nil {
		return m.HairColor
	}
	return ""
}

func (m *Person) GetSkinColor() string {
	if m != nil {
		return m.SkinColor
	}
	return ""
}

func (m *Person) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *Person) GetMass() string {
	if m != nil {
		return m.Mass
	}
	return ""
}

func (m *Person) GetHomeworld() int32 {
	if m != nil {
		return m.Homeworld
	}
	return 0
}

func (m *Person) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Person) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Person) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Person) GetFilms() []int32 {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Person) GetStarships() []int32 {
	if m != nil {
		return m.Starships
	}
	return nil
}

func (m *Person) GetSpecies() []int32 {
	if m != nil {
		return m.Species
	}
	return nil
}

func (m *Person) GetVehicles() []int32 {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

type PeopleReply struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PeopleReply) Reset()         { *m = PeopleReply{} }
func (m *PeopleReply) String() string { return proto.CompactTextString(m) }
func (*PeopleReply) ProtoMessage()    {}
func (*PeopleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{5}
}

func (m *PeopleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleReply.Unmarshal(m, b)
}
func (m *PeopleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleReply.Marshal(b, m, deterministic)
}
func (m *PeopleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleReply.Merge(m, src)
}
func (m *PeopleReply) XXX_Size() int {
	return xxx_messageInfo_PeopleReply.Size(m)
}
func (m *PeopleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleReply.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleReply proto.InternalMessageInfo

func (m *PeopleReply) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type PlanetsRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlanetsRequest) Reset()         { *m = PlanetsRequest{} }
func (m *PlanetsRequest) String() string { return proto.CompactTextString(m) }
func (*PlanetsRequest) ProtoMessage()    {}
func (*PlanetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{6}
}

func (m *PlanetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetsRequest.Unmarshal(m, b)
}
func (m *PlanetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetsRequest.Marshal(b, m, deterministic)
}
func (m *PlanetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetsRequest.Merge(m, src)
}
func (m *PlanetsRequest) XXX_Size() int {
	return xxx_messageInfo_PlanetsRequest.Size(m)
}
func (m *PlanetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetsRequest proto.InternalMessageInfo

func (m *PlanetsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlanetsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Planet struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Population           string   `protobuf:"bytes,3,opt,name=population,proto3" json:"population,omitempty"`
	Diameter             string   `protobuf:"bytes,4,opt,name=diameter,proto3" json:"diameter,omitempty"`
	Gravity              string   `protobuf:"bytes,5,opt,name=gravity,proto3" json:"gravity,omitempty"`
	Climate              string   `protobuf:"bytes,6,opt,name=climate,proto3" json:"climate,omitempty"`
	Terrain              string   `protobuf:"bytes,7,opt,name=terrain,proto3" json:"terrain,omitempty"`
	RotationPeriod       string   `protobuf:"bytes,8,opt,name=rotation_period,json=rotationPeriod,proto3" json:"rotation_period,omitempty"`
	OrbitalPeriod        string   `protobuf:"bytes,9,opt,name=orbital_period,json=orbitalPeriod,proto3" json:"orbital_period,omitempty"`
	SurfaceWater         string   `protobuf:"bytes,10,opt,name=surface_water,json=surfaceWater,proto3" json:"surface_water,omitempty"`
	Url                  string   `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Created              string   `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,13,opt,name=edited,proto3" json:"edited,omitempty"`
	Residents            []int32  `protobuf:"varint,14,rep,packed,name=residents,proto3" json:"residents,omitempty"`
	Films                []int32  `protobuf:"varint,15,rep,packed,name=films,proto3" json:"films,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Planet) Reset()         { *m = Planet{} }
func (m *Planet) String() string { return proto.CompactTextString(m) }
func (*Planet) ProtoMessage()    {}
func (*Planet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{7}
}

func (m *Planet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Planet.Unmarshal(m, b)
}
func (m *Planet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Planet.Marshal(b, m, deterministic)
}
func (m *Planet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planet.Merge(m, src)
}
func (m *Planet) XXX_Size() int {
	return xxx_messageInfo_Planet.Size(m)
}
func (m *Planet) XXX_DiscardUnknown() {
	xxx_messageInfo_Planet.DiscardUnknown(m)
}

var xxx_messageInfo_Planet proto.InternalMessageInfo

func (m *Planet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Planet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Planet) GetPopulation() string {
	if m != nil {
		return m.Population
	}
	return ""
}

func (m *Planet) GetDiameter() string {
	if m != nil {
		return m.Diameter
	}
	return ""
}

func (m *Planet) GetGravity() string {
	if m != nil {
		return m.Gravity
	}
	return ""
}

func (m *Planet) GetClimate() string {
	if m != nil {
		return m.Climate
	}
	return ""
}

func (m *Planet) GetTerrain() string {
	if m != nil {
		return m.Terrain
	}
	return ""
}

func (m *Planet) GetRotationPeriod() string {
	if m != nil {
		return m.RotationPeriod
	}
	return ""
}

func (m *Planet) GetOrbitalPeriod() string {
	if m != nil {
		return m.OrbitalPeriod
	}
	return ""
}

func (m *Planet) GetSurfaceWater() string {
	if m != nil {
		return m.SurfaceWater
	}
	return ""
}

func (m *Planet) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Planet) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Planet) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Planet) GetResidents() []int32 {
	if m != nil {
		return m.Residents
	}
	return nil
}

func (m *Planet) GetFilms() []int32 {
	if m != nil {
		return m.Films
	}
	return nil
}

type PlanetsReply struct {
	Planets              []*Planet `protobuf:"bytes,1,rep,name=planets,proto3" json:"planets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlanetsReply) Reset()         { *m = PlanetsReply{} }
func (m *PlanetsReply) String() string { return proto.CompactTextString(m) }
func (*PlanetsReply) ProtoMessage()    {}
func (*PlanetsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{8}
}

func (m *PlanetsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanetsReply.Unmarshal(m, b)
}
func (m *PlanetsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanetsReply.Marshal(b, m, deterministic)
}
func (m *PlanetsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetsReply.Merge(m, src)
}
func (m *PlanetsReply) XXX_Size() int {
	return xxx_messageInfo_PlanetsReply.Size(m)
}
func (m *PlanetsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetsReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetsReply proto.InternalMessageInfo

func (m *PlanetsReply) GetPlanets() []*Planet {
	if m != nil {
		return m.Planets
	}
	return nil
}

type SpeciesRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpeciesRequest) Reset()         { *m = SpeciesRequest{} }
func (m *SpeciesRequest) String() string { return proto.CompactTextString(m) }
func (*SpeciesRequest) ProtoMessage()    {}
func (*SpeciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{9}
}

func (m *SpeciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeciesRequest.Unmarshal(m, b)
}
func (m *SpeciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeciesRequest.Marshal(b, m, deterministic)
}
func (m *SpeciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeciesRequest.Merge(m, src)
}
func (m *SpeciesRequest) XXX_Size() int {
	return xxx_messageInfo_SpeciesRequest.Size(m)
}
func (m *SpeciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpeciesRequest proto.InternalMessageInfo

func (m *SpeciesRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SpeciesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Species struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Classification       string   `protobuf:"bytes,3,opt,name=classification,proto3" json:"classification,omitempty"`
	Designation          string   `protobuf:"bytes,4,opt,name=designation,proto3" json:"designation,omitempty"`
	AverageHeight        string   `protobuf:"bytes,5,opt,name=average_height,json=averageHeight,proto3" json:"average_height,omitempty"`
	AverageLifespan      string   `protobuf:"bytes,6,opt,name=average_lifespan,json=averageLifespan,proto3" json:"average_lifespan,omitempty"`
	EyeColors            string   `protobuf:"bytes,7,opt,name=eye_colors,json=eyeColors,proto3" json:"eye_colors,omitempty"`
	HairColors           string   `protobuf:"bytes,8,opt,name=hair_colors,json=hairColors,proto3" json:"hair_colors,omitempty"`
	SkinColors           string   `protobuf:"bytes,9,opt,name=skin_colors,json=skinColors,proto3" json:"skin_colors,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	Homeworld            int32    `protobuf:"varint,11,opt,name=homeworld,proto3" json:"homeworld,omitempty"`
	Url                  string   `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	Created              string   `protobuf:"bytes,13,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,14,opt,name=edited,proto3" json:"edited,omitempty"`
	People               []int32  `protobuf:"varint,15,rep,packed,name=people,proto3" json:"people,omitempty"`
	Films                []int32  `protobuf:"varint,16,rep,packed,name=films,proto3" json:"films,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Species) Reset()         { *m = Species{} }
func (m *Species) String() string { return proto.CompactTextString(m) }
func (*Species) ProtoMessage()    {}
func (*Species) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{10}
}

func (m *Species) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Species.Unmarshal(m, b)
}
func (m *Species) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Species.Marshal(b, m, deterministic)
}
func (m *Species) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Species.Merge(m, src)
}
func (m *Species) XXX_Size() int {
	return xxx_messageInfo_Species.Size(m)
}
func (m *Species) XXX_DiscardUnknown() {
	xxx_messageInfo_Species.DiscardUnknown(m)
}

var xxx_messageInfo_Species proto.InternalMessageInfo

func (m *Species) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Species) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Species) GetClassification() string {
	if m != nil {
		return m.Classification
	}
	return ""
}

func (m *Species) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *Species) GetAverageHeight() string {
	if m != nil {
		return m.AverageHeight
	}
	return ""
}

func (m *Species) GetAverageLifespan() string {
	if m != nil {
		return m.AverageLifespan
	}
	return ""
}

func (m *Species) GetEyeColors() string {
	if m != nil {
		return m.EyeColors
	}
	return ""
}

func (m *Species) GetHairColors() string {
	if m != nil {
		return m.HairColors
	}
	return ""
}

func (m *Species) GetSkinColors() string {
	if m != nil {
		return m.SkinColors
	}
	return ""
}

func (m *Species) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Species) GetHomeworld() int32 {
	if m != nil {
		return m.Homeworld
	}
	return 0
}

func (m *Species) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Species) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Species) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Species) GetPeople() []int32 {
	if m != nil {
		return m.People
	}
	return nil
}

func (m *Species) GetFilms() []int32 {
	if m != nil {
		return m.Films
	}
	return nil
}

type SpeciesReply struct {
	Species              []*Species `protobuf:"bytes,1,rep,name=species,proto3" json:"species,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SpeciesReply) Reset()         { *m = SpeciesReply{} }
func (m *SpeciesReply) String() string { return proto.CompactTextString(m) }
func (*SpeciesReply) ProtoMessage()    {}
func (*SpeciesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{11}
}

func (m *SpeciesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpeciesReply.Unmarshal(m, b)
}
func (m *SpeciesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpeciesReply.Marshal(b, m, deterministic)
}
func (m *SpeciesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpeciesReply.Merge(m, src)
}
func (m *SpeciesReply) XXX_Size() int {
	return xxx_messageInfo_SpeciesReply.Size(m)
}
func (m *SpeciesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SpeciesReply.DiscardUnknown(m)
}

var xxx_messageInfo_SpeciesReply proto.InternalMessageInfo

func (m *SpeciesReply) GetSpecies() []*Species {
	if m != nil {
		return m.Species
	}
	return nil
}

type StarshipsRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StarshipsRequest) Reset()         { *m = StarshipsRequest{} }
func (m *StarshipsRequest) String() string { return proto.CompactTextString(m) }
func (*StarshipsRequest) ProtoMessage()    {}
func (*StarshipsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{12}
}

func (m *StarshipsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StarshipsRequest.Unmarshal(m, b)
}
func (m *StarshipsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StarshipsRequest.Marshal(b, m, deterministic)
}
func (m *StarshipsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StarshipsRequest.Merge(m, src)
}
func (m *StarshipsRequest) XXX_Size() int {
	return xxx_messageInfo_StarshipsRequest.Size(m)
}
func (m *StarshipsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StarshipsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StarshipsRequest proto.InternalMessageInfo

func (m *StarshipsRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StarshipsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StarshipsRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

type Starship struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	StarshipClass        string   `protobuf:"bytes,4,opt,name=starship_class,json=starshipClass,proto3" json:"starship_class,omitempty"`
	Manufacturer         string   `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	CostInCredits        string   `protobuf:"bytes,6,opt,name=cost_in_credits,json=costInCredits,proto3" json:"cost_in_credits,omitempty"`
	Length               string   `protobuf:"bytes,7,opt,name=length,proto3" json:"length,omitempty"`
	Crew                 string   `protobuf:"bytes,8,opt,name=crew,proto3" json:"crew,omitempty"`
	Passengers           string   `protobuf:"bytes,9,opt,name=passengers,proto3" json:"passengers,omitempty"`
	MaxAtmospheringSpeed string   `protobuf:"bytes,10,opt,name=max_atmosphering_speed,json=maxAtmospheringSpeed,proto3" json:"max_atmosphering_speed,omitempty"`
	HyperdriveRating     string   `protobuf:"bytes,11,opt,name=hyperdrive_rating,json=hyperdriveRating,proto3" json:"hyperdrive_rating,omitempty"`
	MGLT                 string   `protobuf:"bytes,12,opt,name=MGLT,proto3" json:"MGLT,omitempty"`
	CargoCapacity        string   `protobuf:"bytes,13,opt,name=cargo_capacity,json=cargoCapacity,proto3" json:"cargo_capacity,omitempty"`
	Consumables          string   `protobuf:"bytes,14,opt,name=consumables,proto3" json:"consumables,omitempty"`
	Url                  string   `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	Created              string   `protobuf:"bytes,16,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,17,opt,name=edited,proto3" json:"edited,omitempty"`
	Films                []int32  `protobuf:"varint,18,rep,packed,name=films,proto3" json:"films,omitempty"`
	Pilots               []int32  `protobuf:"varint,19,rep,packed,name=pilots,proto3" json:"pilots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Starship) Reset()         { *m = Starship{} }
func (m *Starship) String() string { return proto.CompactTextString(m) }
func (*Starship) ProtoMessage()    {}
func (*Starship) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{13}
}

func (m *Starship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Starship.Unmarshal(m, b)
}
func (m *Starship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Starship.Marshal(b, m, deterministic)
}
func (m *Starship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Starship.Merge(m, src)
}
func (m *Starship) XXX_Size() int {
	return xxx_messageInfo_Starship.Size(m)
}
func (m *Starship) XXX_DiscardUnknown() {
	xxx_messageInfo_Starship.DiscardUnknown(m)
}

var xxx_messageInfo_Starship proto.InternalMessageInfo

func (m *Starship) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Starship) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Starship) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Starship) GetStarshipClass() string {
	if m != nil {
		return m.StarshipClass
	}
	return ""
}

func (m *Starship) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Starship) GetCostInCredits() string {
	if m != nil {
		return m.CostInCredits
	}
	return ""
}

func (m *Starship) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *Starship) GetCrew() string {
	if m != nil {
		return m.Crew
	}
	return ""
}

func (m *Starship) GetPassengers() string {
	if m != nil {
		return m.Passengers
	}
	return ""
}

func (m *Starship) GetMaxAtmospheringSpeed() string {
	if m != nil {
		return m.MaxAtmospheringSpeed
	}
	return ""
}

func (m *Starship) GetHyperdriveRating() string {
	if m != nil {
		return m.HyperdriveRating
	}
	return ""
}

func (m *Starship) GetMGLT() string {
	if m != nil {
		return m.MGLT
	}
	return ""
}

func (m *Starship) GetCargoCapacity() string {
	if m != nil {
		return m.CargoCapacity
	}
	return ""
}

func (m *Starship) GetConsumables() string {
	if m != nil {
		return m.Consumables
	}
	return ""
}

func (m *Starship) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Starship) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Starship) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Starship) GetFilms() []int32 {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Starship) GetPilots() []int32 {
	if m != nil {
		return m.Pilots
	}
	return nil
}

type StarshipsReply struct {
	Starships            []*Starship `protobuf:"bytes,1,rep,name=starships,proto3" json:"starships,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StarshipsReply) Reset()         { *m = StarshipsReply{} }
func (m *StarshipsReply) String() string { return proto.CompactTextString(m) }
func (*StarshipsReply) ProtoMessage()    {}
func (*StarshipsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{14}
}

func (m *StarshipsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StarshipsReply.Unmarshal(m, b)
}
func (m *StarshipsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StarshipsReply.Marshal(b, m, deterministic)
}
func (m *StarshipsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StarshipsReply.Merge(m, src)
}
func (m *StarshipsReply) XXX_Size() int {
	return xxx_messageInfo_StarshipsReply.Size(m)
}
func (m *StarshipsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StarshipsReply.DiscardUnknown(m)
}

var xxx_messageInfo_StarshipsReply proto.InternalMessageInfo

func (m *StarshipsReply) GetStarships() []*Starship {
	if m != nil {
		return m.Starships
	}
	return nil
}

type VehiclesRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VehiclesRequest) Reset()         { *m = VehiclesRequest{} }
func (m *VehiclesRequest) String() string { return proto.CompactTextString(m) }
func (*VehiclesRequest) ProtoMessage()    {}
func (*VehiclesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{15}
}

func (m *VehiclesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehiclesRequest.Unmarshal(m, b)
}
func (m *VehiclesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehiclesRequest.Marshal(b, m, deterministic)
}
func (m *VehiclesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehiclesRequest.Merge(m, src)
}
func (m *VehiclesRequest) XXX_Size() int {
	return xxx_messageInfo_VehiclesRequest.Size(m)
}
func (m *VehiclesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VehiclesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VehiclesRequest proto.InternalMessageInfo

func (m *VehiclesRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VehiclesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VehiclesRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

type Vehicle struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	VehicleClass         string   `protobuf:"bytes,4,opt,name=vehicle_class,json=vehicleClass,proto3" json:"vehicle_class,omitempty"`
	Manufacturer         string   `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Length               string   `protobuf:"bytes,6,opt,name=length,proto3" json:"length,omitempty"`
	CostInCredits        string   `protobuf:"bytes,7,opt,name=cost_in_credits,json=costInCredits,proto3" json:"cost_in_credits,omitempty"`
	Crew                 string   `protobuf:"bytes,8,opt,name=crew,proto3" json:"crew,omitempty"`
	Passengers           string   `protobuf:"bytes,9,opt,name=passengers,proto3" json:"passengers,omitempty"`
	MaxAtmospheringSpeed string   `protobuf:"bytes,10,opt,name=max_atmosphering_speed,json=maxAtmospheringSpeed,proto3" json:"max_atmosphering_speed,omitempty"`
	CargoCapacity        string   `protobuf:"bytes,11,opt,name=cargo_capacity,json=cargoCapacity,proto3" json:"cargo_capacity,omitempty"`
	Consumables          string   `protobuf:"bytes,12,opt,name=consumables,proto3" json:"consumables,omitempty"`
	Url                  string   `protobuf:"bytes,13,opt,name=url,proto3" json:"url,omitempty"`
	Created              string   `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Edited               string   `protobuf:"bytes,15,opt,name=edited,proto3" json:"edited,omitempty"`
	Films                []int32  `protobuf:"varint,16,rep,packed,name=films,proto3" json:"films,omitempty"`
	Pilots               []int32  `protobuf:"varint,17,rep,packed,name=pilots,proto3" json:"pilots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vehicle) Reset()         { *m = Vehicle{} }
func (m *Vehicle) String() string { return proto.CompactTextString(m) }
func (*Vehicle) ProtoMessage()    {}
func (*Vehicle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{16}
}

func (m *Vehicle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vehicle.Unmarshal(m, b)
}
func (m *Vehicle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vehicle.Marshal(b, m, deterministic)
}
func (m *Vehicle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vehicle.Merge(m, src)
}
func (m *Vehicle) XXX_Size() int {
	return xxx_messageInfo_Vehicle.Size(m)
}
func (m *Vehicle) XXX_DiscardUnknown() {
	xxx_messageInfo_Vehicle.DiscardUnknown(m)
}

var xxx_messageInfo_Vehicle proto.InternalMessageInfo

func (m *Vehicle) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vehicle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vehicle) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Vehicle) GetVehicleClass() string {
	if m != nil {
		return m.VehicleClass
	}
	return ""
}

func (m *Vehicle) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Vehicle) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *Vehicle) GetCostInCredits() string {
	if m != nil {
		return m.CostInCredits
	}
	return ""
}

func (m *Vehicle) GetCrew() string {
	if m != nil {
		return m.Crew
	}
	return ""
}

func (m *Vehicle) GetPassengers() string {
	if m != nil {
		return m.Passengers
	}
	return ""
}

func (m *Vehicle) GetMaxAtmospheringSpeed() string {
	if m != nil {
		return m.MaxAtmospheringSpeed
	}
	return ""
}

func (m *Vehicle) GetCargoCapacity() string {
	if m != nil {
		return m.CargoCapacity
	}
	return ""
}

func (m *Vehicle) GetConsumables() string {
	if m != nil {
		return m.Consumables
	}
	return ""
}

func (m *Vehicle) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Vehicle) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Vehicle) GetEdited() string {
	if m != nil {
		return m.Edited
	}
	return ""
}

func (m *Vehicle) GetFilms() []int32 {
	if m != nil {
		return m.Films
	}
	return nil
}

func (m *Vehicle) GetPilots() []int32 {
	if m != nil {
		return m.Pilots
	}
	return nil
}

type VehiclesReply struct {
	Vehicles             []*Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VehiclesReply) Reset()         { *m = VehiclesReply{} }
func (m *VehiclesReply) String() string { return proto.CompactTextString(m) }
func (*VehiclesReply) ProtoMessage()    {}
func (*VehiclesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd15ecd993b2bac6, []int{17}
}

func (m *VehiclesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehiclesReply.Unmarshal(m, b)
}
func (m *VehiclesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehiclesReply.Marshal(b, m, deterministic)
}
func (m *VehiclesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehiclesReply.Merge(m, src)
}
func (m *VehiclesReply) XXX_Size() int {
	return xxx_messageInfo_VehiclesReply.Size(m)
}
func (m *VehiclesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VehiclesReply.DiscardUnknown(m)
}

var xxx_messageInfo_VehiclesReply proto.InternalMessageInfo

func (m *VehiclesReply) GetVehicles() []*Vehicle {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

func init() {
	proto.RegisterType((*FilmsRequest)(nil), "swapi.FilmsRequest")
	proto.RegisterType((*Film)(nil), "swapi.Film")
	proto.RegisterType((*FilmsReply)(nil), "swapi.FilmsReply")
	proto.RegisterType((*PeopleRequest)(nil), "swapi.PeopleRequest")
	proto.RegisterType((*Person)(nil), "swapi.Person")
	proto.RegisterType((*PeopleReply)(nil), "swapi.PeopleReply")
	proto.RegisterType((*PlanetsRequest)(nil), "swapi.PlanetsRequest")
	proto.RegisterType((*Planet)(nil), "swapi.Planet")
	proto.RegisterType((*PlanetsReply)(nil), "swapi.PlanetsReply")
	proto.RegisterType((*SpeciesRequest)(nil), "swapi.SpeciesRequest")
	proto.RegisterType((*Species)(nil), "swapi.Species")
	proto.RegisterType((*SpeciesReply)(nil), "swapi.SpeciesReply")
	proto.RegisterType((*StarshipsRequest)(nil), "swapi.StarshipsRequest")
	proto.RegisterType((*Starship)(nil), "swapi.Starship")
	proto.RegisterType((*StarshipsReply)(nil), "swapi.StarshipsReply")
	proto.RegisterType((*VehiclesRequest)(nil), "swapi.VehiclesRequest")
	proto.RegisterType((*Vehicle)(nil), "swapi.Vehicle")
	proto.RegisterType((*VehiclesReply)(nil), "swapi.VehiclesReply")
}

func init() { proto.RegisterFile("swapi/swapi.proto", fileDescriptor_cd15ecd993b2bac6) }

var fileDescriptor_cd15ecd993b2bac6 = []byte{
	// 1296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x97, 0xef, 0x6e, 0x1b, 0x45,
	0x17, 0xc6, 0x9b, 0x38, 0xb6, 0xe3, 0x63, 0xaf, 0xed, 0x4c, 0xd3, 0xbc, 0xab, 0xbe, 0xa5, 0x84,
	0xad, 0xda, 0x06, 0x10, 0xad, 0x68, 0x23, 0x15, 0x81, 0x10, 0x42, 0x41, 0x40, 0x45, 0x91, 0x22,
	0x17, 0x81, 0xf8, 0x64, 0x4d, 0x76, 0x4f, 0xd6, 0x23, 0xd6, 0xbb, 0xcb, 0xcc, 0x3a, 0xa9, 0xbf,
	0x71, 0x2f, 0x5c, 0x03, 0x5c, 0x0a, 0xdf, 0xb8, 0x08, 0xee, 0x00, 0xcd, 0xcc, 0x99, 0xfd, 0xe3,
	0x3a, 0x92, 0x43, 0x11, 0x5f, 0xa2, 0x3d, 0xcf, 0x33, 0xb3, 0x59, 0xef, 0xf9, 0xcd, 0x33, 0xb3,
	0xb0, 0xa7, 0x2e, 0x79, 0x2e, 0x1e, 0x9b, 0xbf, 0x8f, 0x72, 0x99, 0x15, 0x19, 0x6b, 0x9b, 0x22,
	0x38, 0x86, 0xc1, 0x97, 0x22, 0x99, 0xab, 0x09, 0xfe, 0xbc, 0x40, 0x55, 0xb0, 0x21, 0x6c, 0x8b,
	0xc8, 0xdf, 0x3a, 0xdc, 0x3a, 0x6a, 0x4f, 0xb6, 0x45, 0xc4, 0xf6, 0xa1, 0x5d, 0x88, 0x22, 0x41,
	0x7f, 0xfb, 0x70, 0xeb, 0xa8, 0x37, 0xb1, 0x45, 0xf0, 0x4b, 0x0b, 0x76, 0xf4, 0xb4, 0xcd, 0x86,
	0xb3, 0x3b, 0xd0, 0xc3, 0x5c, 0xa8, 0x2c, 0xc2, 0xe7, 0x91, 0xdf, 0x32, 0x4e, 0x25, 0xb0, 0xdb,
	0xb0, 0x1b, 0x09, 0x89, 0x61, 0x91, 0x49, 0x7f, 0xc7, 0x98, 0x65, 0xad, 0xbd, 0x5c, 0x66, 0xd1,
	0x22, 0x44, 0xe9, 0xb7, 0xad, 0xe7, 0x6a, 0x76, 0x00, 0x1d, 0x8c, 0x44, 0x81, 0x91, 0xdf, 0x31,
	0x0e, 0x55, 0xec, 0x10, 0xfa, 0x12, 0x13, 0xe4, 0x0a, 0xbf, 0xe0, 0x05, 0xfa, 0x5d, 0x63, 0xd6,
	0x25, 0x36, 0x86, 0xd6, 0x42, 0x26, 0xfe, 0xae, 0x71, 0xf4, 0x25, 0x0b, 0x60, 0x90, 0xe5, 0x98,
	0x8a, 0x34, 0x3e, 0x91, 0xfc, 0x32, 0xf1, 0x7b, 0xc6, 0x6a, 0x68, 0xec, 0x2e, 0x40, 0x38, 0xe3,
	0x92, 0x87, 0x05, 0x4a, 0xe5, 0xc3, 0x61, 0xeb, 0xa8, 0x3d, 0xa9, 0x29, 0xcc, 0x87, 0x6e, 0x9e,
	0xf0, 0x14, 0x0b, 0xe5, 0xf7, 0x8d, 0xe9, 0x4a, 0xed, 0xa8, 0x1c, 0x43, 0x81, 0xca, 0x1f, 0x58,
	0x87, 0x4a, 0xfd, 0x66, 0x54, 0xc1, 0xa5, 0x9a, 0x89, 0x5c, 0xf9, 0x9e, 0xf1, 0x2a, 0x41, 0xff,
	0xfa, 0x0b, 0x9c, 0x89, 0x30, 0x41, 0xe5, 0x0f, 0x8d, 0x59, 0xd6, 0xc1, 0x63, 0x00, 0x6a, 0x5c,
	0x9e, 0x2c, 0xd9, 0x3b, 0xd0, 0x3e, 0xd7, 0x95, 0xbf, 0x75, 0xd8, 0x3a, 0xea, 0x3f, 0xe9, 0x3f,
	0xb2, 0xad, 0xd6, 0x23, 0x26, 0xd6, 0x09, 0x9e, 0x82, 0x77, 0x8a, 0x59, 0x9e, 0xe0, 0x55, 0xad,
	0x66, 0xb0, 0x93, 0xf2, 0xb9, 0x6b, 0x9d, 0xb9, 0x0e, 0x7e, 0x6f, 0x41, 0xe7, 0x14, 0xa5, 0xca,
	0xd2, 0x4d, 0x86, 0xb3, 0xb7, 0x00, 0xce, 0x84, 0x2c, 0x66, 0xd3, 0x25, 0x72, 0xe9, 0x3a, 0x6d,
	0x94, 0x1f, 0x91, 0x9b, 0x8e, 0xc5, 0x98, 0x46, 0xe8, 0xfa, 0x4c, 0x15, 0xfb, 0x3f, 0xf4, 0x70,
	0x89, 0xd3, 0x30, 0x4b, 0xb2, 0xb2, 0xcd, 0xb8, 0xc4, 0x13, 0x5d, 0xeb, 0x7b, 0xce, 0xb8, 0x90,
	0xe4, 0xda, 0x56, 0xf7, 0xb4, 0x52, 0xda, 0xea, 0x27, 0x91, 0x92, 0x6d, 0x9b, 0xdd, 0xd3, 0x8a,
	0xb5, 0x0f, 0xa0, 0x33, 0x43, 0x11, 0xcf, 0x0a, 0xea, 0x36, 0x55, 0xfa, 0xe9, 0xe7, 0x5c, 0x29,
	0x6a, 0xb4, 0xb9, 0xd6, 0xcd, 0x98, 0x65, 0x73, 0xbc, 0xcc, 0x64, 0x12, 0xf9, 0x60, 0x7e, 0x68,
	0x25, 0x38, 0x68, 0xfa, 0x15, 0x34, 0x3e, 0x74, 0x43, 0x89, 0x5c, 0x13, 0x38, 0x30, 0xaa, 0x2b,
	0x6b, 0x68, 0x7a, 0x0d, 0x34, 0xf7, 0x5d, 0x9b, 0x6c, 0x37, 0x6d, 0xd1, 0x84, 0x60, 0xb4, 0x0a,
	0x41, 0x0d, 0x9e, 0x71, 0x13, 0x9e, 0x3a, 0x1e, 0x7b, 0x2b, 0x78, 0x1c, 0x43, 0xdf, 0x75, 0x5b,
	0xf3, 0x71, 0x1f, 0x3a, 0xb9, 0x29, 0x09, 0x10, 0x8f, 0x00, 0xb1, 0xbd, 0x9d, 0x90, 0x19, 0x1c,
	0xc3, 0xf0, 0xd4, 0x32, 0x7b, 0x1d, 0x48, 0x7e, 0xd5, 0x90, 0x98, 0x69, 0x1b, 0x41, 0x72, 0x17,
	0x20, 0xcf, 0xf2, 0x45, 0xc2, 0x0b, 0x91, 0xa5, 0x04, 0x49, 0x4d, 0xb1, 0x79, 0xc0, 0xe7, 0x58,
	0x60, 0x2d, 0x0f, 0x6c, 0xad, 0x5f, 0x46, 0x2c, 0xf9, 0x85, 0x28, 0x96, 0xc4, 0x89, 0x2b, 0x4d,
	0x33, 0x12, 0x31, 0xd7, 0x2b, 0xbe, 0x43, 0xcd, 0xb0, 0xa5, 0x76, 0x0a, 0x94, 0x92, 0x8b, 0x94,
	0xf0, 0x70, 0x25, 0x7b, 0x08, 0x23, 0x99, 0x15, 0xe6, 0xbf, 0x4e, 0x73, 0x94, 0x22, 0x8b, 0x88,
	0x92, 0xa1, 0x93, 0x4f, 0x8d, 0xca, 0xee, 0xc3, 0x30, 0x93, 0x67, 0xa2, 0xe0, 0x89, 0x1b, 0x67,
	0xb9, 0xf1, 0x48, 0xa5, 0x61, 0xf7, 0xc0, 0x53, 0x0b, 0x79, 0xce, 0x43, 0x9c, 0x5e, 0x72, 0xfd,
	0xf8, 0x60, 0x63, 0x84, 0xc4, 0x1f, 0xb4, 0xf6, 0xaf, 0x70, 0x74, 0x07, 0x7a, 0x12, 0x95, 0x88,
	0x30, 0x2d, 0x1c, 0x4b, 0x95, 0x50, 0x51, 0x36, 0xaa, 0x51, 0x16, 0x3c, 0x83, 0x41, 0xd9, 0x5b,
	0x8d, 0xc4, 0xc3, 0x2a, 0xae, 0x56, 0x98, 0x30, 0x6a, 0x99, 0x5e, 0x1a, 0x8a, 0x97, 0x96, 0xb8,
	0xeb, 0x40, 0xf1, 0x47, 0x0b, 0xba, 0x34, 0x6d, 0x23, 0x2a, 0x1e, 0xc0, 0x30, 0x4c, 0xb8, 0x52,
	0xe2, 0x5c, 0x84, 0x75, 0x32, 0x56, 0x54, 0x9d, 0xee, 0x11, 0x2a, 0x11, 0xa7, 0x76, 0x90, 0x05,
	0xa4, 0x2e, 0xe9, 0x66, 0xf1, 0x0b, 0x94, 0x3c, 0xc6, 0x29, 0x2d, 0x7d, 0x8b, 0x8a, 0x47, 0xea,
	0xd7, 0x36, 0x01, 0xde, 0x85, 0xb1, 0x1b, 0x96, 0x88, 0x73, 0x54, 0x39, 0x4f, 0x89, 0x9c, 0x11,
	0xe9, 0x2f, 0x48, 0xd6, 0x19, 0x53, 0xe6, 0x93, 0x72, 0x19, 0xe3, 0x02, 0x4a, 0xb1, 0xb7, 0xa1,
	0x5f, 0x25, 0x94, 0x22, 0x84, 0xa0, 0x8c, 0x28, 0x33, 0xa0, 0xca, 0x28, 0x97, 0x39, 0x50, 0x86,
	0x94, 0x59, 0xc9, 0x09, 0x4f, 0xe3, 0x05, 0x8f, 0x91, 0x98, 0x29, 0xeb, 0x66, 0x2a, 0xf5, 0xaf,
	0x48, 0xa5, 0xc1, 0x5a, 0x9a, 0xbc, 0xab, 0x68, 0x1a, 0x36, 0x68, 0x3a, 0x28, 0xc3, 0xc1, 0x02,
	0x43, 0x55, 0xc5, 0xd1, 0xb8, 0xce, 0xd1, 0x47, 0x30, 0x28, 0x71, 0xd0, 0x1c, 0x1d, 0x55, 0xf9,
	0x64, 0x39, 0x1a, 0x12, 0x47, 0x6e, 0x94, 0xb3, 0x83, 0x17, 0x30, 0x7e, 0xe9, 0x62, 0xed, 0x1a,
	0x28, 0xe9, 0xe7, 0x98, 0x67, 0x11, 0x26, 0x44, 0x84, 0x2d, 0x82, 0xdf, 0x76, 0x60, 0xd7, 0xdd,
	0xee, 0x9f, 0xdf, 0x46, 0xd3, 0xe2, 0xb2, 0x76, 0x6a, 0x50, 0x23, 0xa4, 0x3c, 0xa7, 0x9e, 0x68,
	0x51, 0x1f, 0x10, 0xe6, 0x3c, 0x5d, 0x9c, 0xf3, 0xb0, 0x58, 0xc8, 0xf2, 0x30, 0xd2, 0xd0, 0xd8,
	0x03, 0x18, 0x85, 0x99, 0x2a, 0xa6, 0xba, 0xd3, 0x52, 0xbf, 0x5b, 0x45, 0x40, 0x79, 0x5a, 0x7e,
	0x9e, 0x9e, 0x58, 0x51, 0xbf, 0xef, 0x04, 0xd3, 0xb8, 0x98, 0x11, 0x4a, 0x54, 0xe9, 0x87, 0x0e,
	0x25, 0x5e, 0x12, 0x40, 0xe6, 0xda, 0x84, 0x25, 0x57, 0x0a, 0xd3, 0x18, 0x2b, 0x72, 0x2a, 0x85,
	0x1d, 0xc3, 0xc1, 0x9c, 0xbf, 0x9a, 0xf2, 0x62, 0x9e, 0xa9, 0x7c, 0x86, 0x52, 0xa4, 0xf1, 0x54,
	0xe5, 0x88, 0x11, 0x71, 0xb4, 0x3f, 0xe7, 0xaf, 0x3e, 0xaf, 0x99, 0x2f, 0xb5, 0xc7, 0xde, 0x87,
	0xbd, 0xd9, 0x32, 0x47, 0x19, 0x49, 0x71, 0x81, 0x53, 0xc9, 0x0b, 0x91, 0xc6, 0x94, 0x48, 0xe3,
	0xca, 0x98, 0x18, 0x5d, 0x3f, 0xd6, 0xb7, 0x5f, 0xbd, 0xf8, 0x8e, 0x18, 0x33, 0xd7, 0xfa, 0xad,
	0x85, 0x5c, 0xc6, 0xd9, 0x34, 0xe4, 0x39, 0x0f, 0x75, 0x1c, 0x7b, 0xf4, 0x4b, 0xb5, 0x7a, 0x42,
	0xa2, 0x5e, 0xac, 0x61, 0x96, 0xaa, 0xc5, 0x9c, 0x9f, 0xd9, 0x33, 0x8c, 0x59, 0xac, 0x35, 0xc9,
	0xf1, 0x3b, 0x5a, 0xcb, 0xef, 0xf8, 0x2a, 0x7e, 0xf7, 0xd6, 0xef, 0xaa, 0xac, 0xbe, 0xab, 0x6a,
	0xaa, 0x45, 0x92, 0x15, 0xca, 0xbf, 0x49, 0x54, 0x9b, 0x2a, 0xf8, 0x0c, 0x86, 0x35, 0x0a, 0x35,
	0xc1, 0x1f, 0xd4, 0xf7, 0x5f, 0xcb, 0xf0, 0xc8, 0x31, 0x4c, 0x7a, 0x6d, 0x43, 0x0e, 0xbe, 0x81,
	0xd1, 0xf7, 0xb4, 0xcd, 0xbe, 0x39, 0xc5, 0x7f, 0xb5, 0xa0, 0x4b, 0x77, 0x7b, 0x03, 0x88, 0xef,
	0x81, 0x47, 0x3b, 0x7f, 0x83, 0xe1, 0x01, 0x89, 0x9b, 0x23, 0x5c, 0xa1, 0xd9, 0x69, 0xa0, 0xb9,
	0x06, 0xed, 0xee, 0x3a, 0xb4, 0xff, 0x3b, 0x84, 0x5f, 0x27, 0xb0, 0xbf, 0x01, 0x81, 0x83, 0x2b,
	0x09, 0xf4, 0xd6, 0x12, 0x38, 0xbc, 0x8a, 0xc0, 0xd1, 0x7a, 0x02, 0xc7, 0xeb, 0x09, 0xdc, 0x6b,
	0x10, 0xf8, 0x09, 0x78, 0x15, 0x40, 0x1a, 0xc0, 0xf7, 0x6a, 0x07, 0xb9, 0x66, 0x86, 0xd2, 0xb8,
	0xea, 0x60, 0xf7, 0xe4, 0xcf, 0x6d, 0xb0, 0x9f, 0x6e, 0xec, 0x43, 0x68, 0x9b, 0x2f, 0x00, 0x76,
	0xb3, 0x76, 0xda, 0x77, 0x48, 0xde, 0xde, 0x6b, 0x8a, 0x79, 0xb2, 0x0c, 0x6e, 0xb0, 0x63, 0x7d,
	0x9a, 0xb7, 0xd9, 0x5e, 0x1e, 0x00, 0x6b, 0x9f, 0x04, 0xb7, 0xd9, 0x8a, 0x6a, 0x67, 0x3d, 0x83,
	0x2e, 0x9d, 0x1c, 0xd8, 0xad, 0xc6, 0x19, 0xa1, 0xfc, 0x67, 0x37, 0x57, 0xe5, 0x72, 0xa2, 0x3b,
	0x02, 0xdc, 0x5a, 0xd9, 0x14, 0x56, 0x26, 0xd6, 0x77, 0x94, 0xe0, 0x06, 0xfb, 0x14, 0x7a, 0xe5,
	0x1a, 0x65, 0xff, 0x5b, 0x59, 0x8b, 0xe5, 0xe4, 0x5b, 0xaf, 0x1b, 0x76, 0xfa, 0xc7, 0xb0, 0xeb,
	0x5e, 0x30, 0x3b, 0x68, 0xbe, 0xc9, 0x72, 0xf2, 0xfe, 0x6b, 0xba, 0x99, 0x7b, 0xd6, 0x31, 0x9f,
	0xc7, 0x4f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x8d, 0x5a, 0xa5, 0x33, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwapiClient is the client API for Swapi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwapiClient interface {
	Films(ctx context.Context, in *FilmsRequest, opts ...grpc.CallOption) (*FilmsReply, error)
	People(ctx context.Context, in *PeopleRequest, opts ...grpc.CallOption) (*PeopleReply, error)
	Planets(ctx context.Context, in *PlanetsRequest, opts ...grpc.CallOption) (*PlanetsReply, error)
	Species(ctx context.Context, in *SpeciesRequest, opts ...grpc.CallOption) (*SpeciesReply, error)
	Starships(ctx context.Context, in *StarshipsRequest, opts ...grpc.CallOption) (*StarshipsReply, error)
	Vehicles(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*VehiclesReply, error)
}

type swapiClient struct {
	cc *grpc.ClientConn
}

func NewSwapiClient(cc *grpc.ClientConn) SwapiClient {
	return &swapiClient{cc}
}

func (c *swapiClient) Films(ctx context.Context, in *FilmsRequest, opts ...grpc.CallOption) (*FilmsReply, error) {
	out := new(FilmsReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/Films", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapiClient) People(ctx context.Context, in *PeopleRequest, opts ...grpc.CallOption) (*PeopleReply, error) {
	out := new(PeopleReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/People", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapiClient) Planets(ctx context.Context, in *PlanetsRequest, opts ...grpc.CallOption) (*PlanetsReply, error) {
	out := new(PlanetsReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/Planets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapiClient) Species(ctx context.Context, in *SpeciesRequest, opts ...grpc.CallOption) (*SpeciesReply, error) {
	out := new(SpeciesReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/Species", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapiClient) Starships(ctx context.Context, in *StarshipsRequest, opts ...grpc.CallOption) (*StarshipsReply, error) {
	out := new(StarshipsReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/Starships", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapiClient) Vehicles(ctx context.Context, in *VehiclesRequest, opts ...grpc.CallOption) (*VehiclesReply, error) {
	out := new(VehiclesReply)
	err := c.cc.Invoke(ctx, "/swapi.swapi/Vehicles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapiServer is the server API for Swapi service.
type SwapiServer interface {
	Films(context.Context, *FilmsRequest) (*FilmsReply, error)
	People(context.Context, *PeopleRequest) (*PeopleReply, error)
	Planets(context.Context, *PlanetsRequest) (*PlanetsReply, error)
	Species(context.Context, *SpeciesRequest) (*SpeciesReply, error)
	Starships(context.Context, *StarshipsRequest) (*StarshipsReply, error)
	Vehicles(context.Context, *VehiclesRequest) (*VehiclesReply, error)
}

func RegisterSwapiServer(s *grpc.Server, srv SwapiServer) {
	s.RegisterService(&_Swapi_serviceDesc, srv)
}

func _Swapi_Films_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).Films(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/Films",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).Films(ctx, req.(*FilmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swapi_People_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeopleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).People(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/People",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).People(ctx, req.(*PeopleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swapi_Planets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).Planets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/Planets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).Planets(ctx, req.(*PlanetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swapi_Species_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).Species(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/Species",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).Species(ctx, req.(*SpeciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swapi_Starships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).Starships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/Starships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).Starships(ctx, req.(*StarshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Swapi_Vehicles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiclesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapiServer).Vehicles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapi.swapi/Vehicles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapiServer).Vehicles(ctx, req.(*VehiclesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Swapi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swapi.swapi",
	HandlerType: (*SwapiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Films",
			Handler:    _Swapi_Films_Handler,
		},
		{
			MethodName: "People",
			Handler:    _Swapi_People_Handler,
		},
		{
			MethodName: "Planets",
			Handler:    _Swapi_Planets_Handler,
		},
		{
			MethodName: "Species",
			Handler:    _Swapi_Species_Handler,
		},
		{
			MethodName: "Starships",
			Handler:    _Swapi_Starships_Handler,
		},
		{
			MethodName: "Vehicles",
			Handler:    _Swapi_Vehicles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swapi/swapi.proto",
}
